--
-- Author: HLZ
-- Date: 2016-01-06 16:27:07
-- 自定义事件名称 对应g_EventDispatch的事件名


--Test
TEST_EVENT_RETURN = "TEST_EVENT_RETURN"


--怪兽第一阶段孵化
HATCHERY_START_LV1_MONSTER = "HATCHERY_START_LV1_MONSTER"
--怪兽第二阶段孵化
HATCHERY_START_LV2_MONSTER = "HATCHERY_START_LV1_MONSTER"
--怪兽第三阶段孵化
HATCHERY_START_LV3_MONSTER = "HATCHERY_START_LV1_MONSTER"

--刷新饱食值道具
RERESH_SATIATION_ITEMS = "RERESH_SATIATION_ITEMS"

--刷新进化值道具
REFRESH_Evolution_ITEMS = "REFRESH_Evolution_ITEMS"

--刷新世界树果实
--Yggdrasil fruit
REFRESH_YGGDRASIL_FRUITS = "REFRESH_YGGDRASIL_FRUITS"




