--
-- Author: HLZ
-- Date: 2016-01-06 16:27:07
-- 自定义事件名称 对应g_EventDispatch的事件名


--Test
TEST_EVENT_RETURN = "TEST_EVENT_RETURN"


--怪兽阶段刷新
BATTLE_STAGE_REFRESH = "BATTLE_STAGE_REFRESH"


--战斗结束 
BATTLE_STATE_END = "BATTLE_STATE_END"

--刷新面板UI 角色信息
REFRESH_PLAYER_INFO = "REFRESH_PLAYER_INFO"

--刷新饱食值道具
RERESH_SATIATION_ITEMS = "RERESH_SATIATION_ITEMS"

--刷新进化值道具
REFRESH_Evolution_ITEMS = "REFRESH_Evolution_ITEMS"

--刷新世界树果实
--Yggdrasil fruit
REFRESH_YGGDRASIL_FRUITS = "REFRESH_YGGDRASIL_FRUITS"

--新的怪物日志ID推送
BATTLE_NEW_BEHAVIORLOG_BTN = "BATTLE_NEW_BEHAVIORLOG_BTN"

--新的怪物日志推送
BATTLE_NEW_BEHAVIORLOG = "BATTLE_NEW_BEHAVIORLOG"






