-- auto generated by tools , do not modify, designer excel table data

--- @module Table

--- @field [parent=#global] #Table Table

module("Table")

--- @field [parent=#Table] #Monster Monster

--- @function [parent=#Monster] get
-- @param #number id 
-- @return #Monster_GetReturn

--- @type Monster_GetReturn
-- @field #number id
-- @field #string name
-- @field #string icon
-- @field #string resName
-- @field #string animName
-- @field #string desc
Monster = {
switch = {id=1,name=2,icon=3,resName=4,animName=5,desc=6},
[10001] = {10001, "幽灵", "", "Ghost_%s_%d.png", "Ghost_", "我是一只小幽灵"},
}
